language: python
sudo: false
cache: pip
dist: trusty

addons:
  apt:
    packages:
      - sqlite3
      - gdal-bin
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev

python:
  - "3.6"

branches:
  only:
    - master

before_install:
  - pip install -U pip wheel setuptools
  - pip install --no-cache-dir -U -r requirements-test.txt
  - ./runflake8
  - ./runcheckmigration
  - ./runisort
  - npm install -g jslint
  - jslint django_loci/static/django-loci/js/*.js

install:
  - python setup.py -q develop
  # temp check
  - pip list

script:
  - pytest --cov=django_loci
  - coverage run -a --source=django_loci runtests.py
  - |
    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      # gets commit message of last commit before pull request merge
      COMMIT_MESSAGE=$(git log $TRAVIS_PULL_REQUEST_SHA --format=%B -n 1)
      printf "Checking commit message:\n\n"
      printf "$COMMIT_MESSAGE\n\n"
      checkcommit --message "$COMMIT_MESSAGE"
    fi

after_success:
  coveralls
